// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRVtI5SZ3X5AouOcBzpNG5MB6GAk2IPqg',
    appId: '1:161292813782:web:fc14ddd94645f429799077',
    messagingSenderId: '161292813782',
    projectId: 'fluttercontinue',
    authDomain: 'fluttercontinue.firebaseapp.com',
    storageBucket: 'fluttercontinue.appspot.com',
    measurementId: 'G-1WWWX5VW76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOFYOMMW3l9TMhzcc1qGJogispPs4flsY',
    appId: '1:161292813782:android:81a10ace88223e49799077',
    messagingSenderId: '161292813782',
    projectId: 'fluttercontinue',
    storageBucket: 'fluttercontinue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUQo-xaJVvsdltkUJ8vfj-ZHzCkl5HWI',
    appId: '1:161292813782:ios:2663bd41f111b037799077',
    messagingSenderId: '161292813782',
    projectId: 'fluttercontinue',
    storageBucket: 'fluttercontinue.appspot.com',
    iosClientId: '161292813782-2359vnr7m009rk1b55ip34t6897pn6th.apps.googleusercontent.com',
    iosBundleId: 'com.reyfernando.firstProject',
  );
}
